# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='summary',
            field=models.CharField(default='default', max_length=150),
        ),
    ]
